# Generated by Django 6.0.3 on 2026-03-25 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(help_text='Auto-generated student number e.g. STD2025001', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_names', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('nationality', models.CharField(default='Ugandan', max_length=50)),
                ('district_of_origin', models.CharField(blank=True, help_text='District of origin in Uganda', max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, choices=[('catholic', 'Roman Catholic'), ('protestant', 'Protestant / Anglican'), ('muslim', 'Muslim'), ('sda', 'Seventh Day Adventist'), ('pentecostal', 'Pentecostal / Born Again'), ('other', 'Other')], max_length=20)),
                ('birth_certificate_no', models.CharField(blank=True, max_length=50, verbose_name='Birth Certificate Number')),
                ('date_enrolled', models.DateField()),
                ('academic_year', models.CharField(help_text='Enrolment year e.g. 2025/2026', max_length=9)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_class', models.CharField(blank=True, help_text='Class attended at previous school', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('secondary_guardian_name', models.CharField(blank=True, max_length=100)),
                ('secondary_guardian_phone', models.CharField(blank=True, max_length=15)),
                ('secondary_guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('medical_notes', models.TextField(blank=True, help_text='Allergies, chronic conditions, special needs, etc.')),
                ('is_special_needs', models.BooleanField(default=False)),
                ('special_needs_notes', models.TextField(blank=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('left_reason', models.CharField(blank=True, help_text='E.g. Transfer, Completed P7, Withdrew', max_length=200)),
                ('current_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.schoolclass')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_number', models.CharField(help_text='Auto-generated e.g. ADM2025001', max_length=20, unique=True)),
                ('academic_year', models.CharField(help_text='Intended year of entry e.g. 2026/2027', max_length=9)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_names', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('nationality', models.CharField(default='Ugandan', max_length=50)),
                ('district_of_origin', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('birth_certificate_no', models.CharField(blank=True, max_length=50)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_class', models.CharField(blank=True, max_length=50)),
                ('last_result', models.CharField(blank=True, help_text='E.g. Promoted with 85%, Division 2', max_length=100)),
                ('parent_full_name', models.CharField(max_length=100)),
                ('parent_relationship', models.CharField(help_text='E.g. Father, Mother, Guardian', max_length=50)),
                ('parent_phone', models.CharField(max_length=15)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('parent_occupation', models.CharField(blank=True, max_length=100)),
                ('parent_address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('enrolled', 'Enrolled')], default='pending', max_length=20)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('admission_date', models.DateField(blank=True, help_text='Date officially admitted / approved', null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_class', models.ForeignKey(help_text='Class the child is applying to join', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_applications', to='academics.schoolclass')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_record', to='students.student')),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'ordering': ['-application_date'],
            },
        ),
    ]
