# Generated by Django 6.0.3 on 2026-04-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classsubject_school_stream_and_more'),
        ('students', '0002_remove_admission_parent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='school_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='academics.schoolstream'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.schoolstream'),
        ),
    ]
