# Generated by Django 6.0.3 on 2026-04-03 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_classsubject_is_active_and_more'),
        ('students', '0003_admission_school_stream_student_school_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.schoolsupportedclasses'),
        ),
    ]
