# Generated by Django 5.1.4 on 2026-04-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_teachersubject_subject'),
        ('students', '0004_alter_student_current_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='applied_class',
            field=models.ForeignKey(help_text='Class the child is applying to join', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_applications', to='academics.schoolsupportedclasses'),
        ),
    ]
