# Generated by Django 6.0.3 on 2026-03-25 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='E.g. "Term 1 BOT Exams 2026" or "P4 Maths Test Week 3"', max_length=200)),
                ('assessment_type', models.CharField(choices=[('bot', 'Beginning of Term Exam (BOT)'), ('mot', 'Middle of Term Exam (MOT)'), ('eot', 'End of Term Exam (EOT)'), ('test', 'Class Test'), ('exercise', 'Exercise / Classwork'), ('quiz', 'Quiz'), ('mock', 'Mock Examination'), ('ple', 'PLE / Prelims'), ('homework', 'Homework'), ('project', 'Project / Assignment'), ('practical', 'Practical / Oral'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Instructions or notes about this assessment')),
                ('paper_file', models.FileField(blank=True, help_text='Upload the exam paper or task sheet (PDF, DOCX, image)', null=True, upload_to='assessments/papers/')),
                ('marking_scheme', models.FileField(blank=True, help_text='Upload the marking guide / answer sheet (optional)', null=True, upload_to='assessments/schemes/')),
                ('academic_year', models.CharField(help_text='Format: 2025/2026', max_length=9)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month this assessment was given')),
                ('date_given', models.DateField(help_text='Date the assessment was administered')),
                ('date_due', models.DateField(blank=True, help_text='Submission deadline (for homework, projects, etc.)', null=True)),
                ('date_results_released', models.DateField(blank=True, help_text='Date results were / will be released', null=True)),
                ('total_marks', models.DecimalField(decimal_places=1, default=100, help_text='Default max marks (used per subject unless overridden)', max_digits=7)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Time allowed in minutes', null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Visible to teachers for mark entry when True')),
                ('results_published', models.BooleanField(default=False, help_text='Results visible to parents on the portal when True')),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_created', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.term')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-date_given', 'assessment_type'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students_invited', models.PositiveIntegerField(default=0, help_text='Students expected to sit')),
                ('students_sat', models.PositiveIntegerField(default=0, help_text='Students who actually sat')),
                ('students_absent', models.PositiveIntegerField(default=0)),
                ('venue', models.CharField(blank=True, choices=[('classroom', 'Own Classroom'), ('hall', 'Assembly Hall'), ('library', 'Library'), ('lab', 'Science / Computer Lab'), ('outdoor', 'Outdoor / Grounds'), ('other', 'Other')], max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('class_remarks', models.CharField(blank=True, max_length=300)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_classes', to='assessments.assessment')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_classes', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assessment_links', to='academics.schoolclass')),
            ],
            options={
                'verbose_name': 'Assessment Class',
                'verbose_name_plural': 'Assessment Classes',
                'ordering': ['assessment', 'school_class'],
                'unique_together': {('assessment', 'school_class')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentPassMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pass_type', models.CharField(choices=[('percentage', 'Percentage of total marks'), ('absolute', 'Absolute marks')], default='percentage', max_length=15)),
                ('pass_value', models.DecimalField(decimal_places=1, help_text='The passmark value. percentage → e.g. 50.0 (means 50%). absolute   → e.g. 45.0 (means 45 marks).', max_digits=6)),
                ('notes', models.CharField(blank=True, help_text='E.g. "Adjusted because paper was difficult"', max_length=200)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Head teacher or admin who approved this passmark', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_marks_approved', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_marks', to='assessments.assessment')),
                ('set_by', models.ForeignKey(blank=True, help_text='The teacher who set this passmark', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_marks_set', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_pass_marks', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Assessment Pass Mark',
                'verbose_name_plural': 'Assessment Pass Marks',
                'ordering': ['assessment', 'subject__sort_order'],
                'unique_together': {('assessment', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=1, help_text='Marks scored (Primary). Leave blank for Nursery.', max_digits=7, null=True)),
                ('total_marks', models.DecimalField(decimal_places=1, help_text='Max marks available for this subject in this assessment', max_digits=7)),
                ('grade', models.CharField(blank=True, choices=[('D1', 'Distinction 1 (90–100%)'), ('D2', 'Distinction 2 (80–89%)'), ('C3', 'Credit 3 (70–79%)'), ('C4', 'Credit 4 (65–69%)'), ('C5', 'Credit 5 (60–64%)'), ('C6', 'Credit 6 (55–59%)'), ('P7', 'Pass 7 (45–54%)'), ('P8', 'Pass 8 (35–44%)'), ('F9', 'Fail 9 (0–34%)')], help_text='Auto-computed UNEB-style grade on save', max_length=5)),
                ('nursery_rating', models.CharField(blank=True, choices=[('EE', 'Exceeds Expectations'), ('ME', 'Meets Expectations'), ('AE', 'Approaching Expectations'), ('NS', 'Needs Support')], help_text='Developmental rating for Nursery (Baby–Top Class)', max_length=5)),
                ('is_pass', models.BooleanField(blank=True, help_text='Auto-computed vs AssessmentPassMark. Null = not yet computed.', null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('absent_reason', models.CharField(blank=True, help_text='E.g. "Sick", "Travel", "Family emergency"', max_length=200)),
                ('remarks', models.CharField(blank=True, help_text='Subject teacher remark e.g. "Excellent" or "Needs more reading"', max_length=300)),
                ('is_verified', models.BooleanField(default=False, help_text='True when marks have been verified by authorised staff')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='assessments.assessment')),
                ('entered_by', models.ForeignKey(blank=True, help_text='Teacher / staff who entered these marks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances_entered', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_performances', to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_performances', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='academics.subject')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Head teacher / second marker who verified the marks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Performance',
                'verbose_name_plural': 'Assessment Performances',
                'ordering': ['assessment', 'school_class', 'student__last_name', 'subject__sort_order'],
                'unique_together': {('assessment', 'student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_marks', models.DecimalField(decimal_places=1, help_text='Max marks for this subject in this assessment', max_digits=7)),
                ('paper_file', models.FileField(blank=True, help_text='Subject-specific paper (if different from main paper)', null=True, upload_to='assessments/subject_papers/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order on report e.g. 1=English, 2=Maths')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_subjects', to='assessments.assessment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assessment_links', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Assessment Subject',
                'verbose_name_plural': 'Assessment Subjects',
                'ordering': ['assessment', 'sort_order', 'subject__sort_order'],
                'unique_together': {('assessment', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('organiser', 'Organiser / Coordinator'), ('invigilator', 'Invigilator'), ('marker', 'Marker / Examiner'), ('setter', 'Paper Setter'), ('class_teacher', 'Class Teacher'), ('supervisor', 'Supervisor')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_teachers', to='assessments.assessment')),
                ('school_class', models.ForeignKey(blank=True, help_text='Class this teacher handled (invigilator / class_teacher)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_assessment_teachers', to='academics.schoolclass')),
                ('subject', models.ForeignKey(blank=True, help_text='Subject this teacher is responsible for (marker / setter)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_assessment_teachers', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assessment_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Teacher',
                'verbose_name_plural': 'Assessment Teachers',
                'ordering': ['assessment', 'role', 'teacher'],
                'unique_together': {('assessment', 'teacher', 'role')},
            },
        ),
    ]
