# Generated by Django 6.0.3 on 2026-04-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classsubject_school_stream_and_more'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentclass',
            name='school_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.schoolstream'),
        ),
        migrations.AddField(
            model_name='assessmentperformance',
            name='school_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_performances', to='academics.schoolstream'),
        ),
        migrations.AddField(
            model_name='assessmentteacher',
            name='school_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_assessment_teachers', to='academics.schoolstream'),
        ),
    ]
