# Generated by Django 6.0.3 on 2026-04-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_assessment_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentpassmark',
            options={'ordering': ['assessment'], 'verbose_name': 'Assessment Pass Mark', 'verbose_name_plural': 'Assessment Pass Marks'},
        ),
        migrations.AlterModelOptions(
            name='assessmentperformance',
            options={'ordering': ['assessment', 'school_class', 'student__last_name'], 'verbose_name': 'Assessment Performance', 'verbose_name_plural': 'Assessment Performances'},
        ),
        migrations.AlterModelOptions(
            name='assessmentsubject',
            options={'ordering': ['assessment', 'sort_order'], 'verbose_name': 'Assessment Subject', 'verbose_name_plural': 'Assessment Subjects'},
        ),
    ]
