# Generated by Django 6.0.3 on 2026-04-20 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_alter_assessmentteacher_school_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modify_class', models.BooleanField(default=True)),
                ('modify_subject', models.BooleanField(default=False)),
                ('modify_total_mark', models.BooleanField(default=False)),
                ('modify_teacher', models.BooleanField(default=False)),
                ('modify_performance', models.BooleanField(default=False)),
                ('edit_once', models.BooleanField(default=False)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modification', to='assessments.assessment')),
            ],
            options={
                'verbose_name': 'Assessment Modification',
                'verbose_name_plural': 'Assessment Modifications',
            },
        ),
    ]
