# Generated by Django 6.0.3 on 2026-04-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_assessmentmodification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPerformanceEntryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_attended', models.PositiveIntegerField(default=0, help_text='Total students enrolled in this class (from AssessmentClass).')),
                ('students_entered', models.PositiveIntegerField(default=0, help_text='Students whose mark for this subject has been saved so far.')),
                ('students_left', models.PositiveIntegerField(default=0, help_text='students_attended − students_entered.')),
                ('students_passed', models.PositiveIntegerField(default=0)),
                ('students_tried', models.PositiveIntegerField(default=0, help_text='Attempted but did not reach the pass mark.')),
                ('attendance_entry_met', models.BooleanField(default=False, help_text='True when students_entered >= students_attended.')),
                ('is_edit_allowed', models.BooleanField(default=False, help_text='Set to True via the enable-edit workflow.')),
                ('is_done', models.BooleanField(default=False, help_text='True when entry is complete and locked.')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_statuses', to='assessments.assessment')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_statuses', to='assessments.assessmentclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_statuses', to='assessments.assessmentsubject')),
            ],
            options={
                'verbose_name': 'Performance Entry Status',
                'verbose_name_plural': 'Performance Entry Statuses',
                'ordering': ['school_class', 'subject'],
                'unique_together': {('assessment', 'school_class', 'subject')},
            },
        ),
    ]
