# Generated by Django 6.0.3 on 2026-05-01 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_year'),
        ('assessments', '0009_assessmentperformanceentrystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentperformance',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_performances', to='academics.schoolsupportedclasses'),
        ),
    ]
