# Generated by Django 5.2.13 on 2026-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_alter_assessmentperformance_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_entry_active',
            field=models.BooleanField(default=False, help_text='True if performance entry is active/open'),
        ),
        migrations.AddField(
            model_name='assessmentsubject',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Total marks for this subject in this assessment', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsubject',
            name='passmark',
            field=models.DecimalField(decimal_places=1, help_text='Pass mark for this subject in this assessment', max_digits=7),
        ),
    ]
