# Generated by Django 6.0.3 on 2026-03-25 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fees_type', models.CharField(choices=[('tuition', 'Tuition Fees'), ('development', 'Development / Building Levy'), ('activity', 'Activity / Games Fees'), ('lunch', 'Lunch / Feeding Fees'), ('transport', 'Transport / Bus Fees'), ('uniform', 'Uniform Fees'), ('boarding', 'Boarding Fees'), ('pta', 'PTA Contribution'), ('exam', 'Examination Fees'), ('admission', 'Admission / Registration Fees'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in Uganda Shillings (UGX)', max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, help_text='Payment deadline for this fee', null=True)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.schoolclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.term')),
            ],
            options={
                'verbose_name': 'School Fees Structure',
                'verbose_name_plural': 'School Fees Structures',
                'ordering': ['term', 'school_class', 'fees_type'],
                'unique_together': {('school_class', 'term', 'fees_type')},
            },
        ),
        migrations.CreateModel(
            name='FeesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(help_text='Auto-generated receipt number e.g. RCP2025001', max_length=30, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in UGX', max_digits=12)),
                ('payment_date', models.DateField()),
                ('school_class', models.ForeignKey(help_text='Which Class the student in', on_delete=django.db.models.deletion.CASCADE, related_name='school_class', to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='academics.term')),
                ('school_fees', models.ForeignKey(help_text='Which fee item this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.schoolfees')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_required', models.DecimalField(decimal_places=2, help_text='Sum of all compulsory fees for this student this term (UGX)', max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid so far this term (UGX)', max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Outstanding balance = total_required − total_paid (UGX)', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Any approved fee discount e.g. staff child, scholarship (UGX)', max_digits=12)),
                ('discount_reason', models.CharField(blank=True, max_length=200)),
                ('is_cleared', models.BooleanField(default=False, help_text='True when balance is fully paid')),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_assessments_generated', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assessments', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_assessments', to='academics.term')),
            ],
            options={
                'verbose_name': 'Fees Assessment',
                'verbose_name_plural': 'Fees Assessments',
                'ordering': ['term__name', 'student__last_name'],
                'unique_together': {('student', 'term')},
            },
        ),
    ]
