# Generated by Django 6.0.3 on 2026-04-22 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_year'),
        ('fees', '0001_initial'),
        ('students', '0002_rename_is_to_class_the_current_studentclasspromotion_has_promoted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholasticRequirementPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(help_text='Auto-generated e.g. SRP2025001', max_length=30, unique=True)),
                ('brought_item', models.BooleanField(default=False, help_text='True if physical items were received in this transaction')),
                ('items_brought', models.PositiveIntegerField(default=0, help_text='Number of physical units received in this transaction')),
                ('brought_cash', models.BooleanField(default=False, help_text='True if a cash payment was received in this transaction')),
                ('amount_paid_ugx', models.DecimalField(decimal_places=2, default=0, help_text='Cash paid in this transaction (UGX). 0 when no cash involved.', max_digits=10)),
                ('paid_fully', models.BooleanField(default=False, help_text='True if this transaction fully settled the requirement for this student')),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholastic_payments_handled', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='fees.schoolscholasticrequirements')),
                ('school_class', models.ForeignKey(help_text="Student's class AT THE TIME of this transaction", on_delete=django.db.models.deletion.CASCADE, related_name='scholastic_payment_records', to='academics.schoolsupportedclasses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholastic_payment_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Scholastic Requirement Payment',
                'verbose_name_plural': 'Scholastic Requirement Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
