# Generated by Django 6.0.3 on 2026-04-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classsubject_school_stream_and_more'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feespayment',
            name='school_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees_payments', to='academics.schoolstream'),
        ),
        migrations.AddField(
            model_name='schoolfees',
            name='school_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees_structures', to='academics.schoolstream'),
        ),
    ]
