# Generated by Django 6.0.3 on 2026-04-03 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_classsubject_is_active_and_more'),
        ('fees', '0002_feespayment_school_stream_schoolfees_school_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolfees',
            name='school_stream',
        ),
        migrations.AddField(
            model_name='schoolfees',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schoolfees',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.schoolsupportedclasses'),
        ),
    ]
