# Generated by Django 6.0.3 on 2026-04-03 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_teachersubject_subject'),
        ('fees', '0003_remove_schoolfees_school_stream_schoolfees_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolfees',
            options={'ordering': ['term', 'fees_type'], 'verbose_name': 'School Fees Structure', 'verbose_name_plural': 'School Fees Structures'},
        ),
        migrations.AlterUniqueTogether(
            name='schoolfees',
            unique_together={('term', 'fees_type')},
        ),
        migrations.CreateModel(
            name='FeesClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_fee_affected_class', to='fees.assessmentfees')),
                ('fees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_school_class', to='fees.schoolfees')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_fees_class', to='academics.schoolsupportedclasses')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='schoolfees',
            name='is_compulsory',
        ),
        migrations.RemoveField(
            model_name='schoolfees',
            name='school_class',
        ),
    ]
