# Generated by Django 6.0.3 on 2026-04-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_schoolfees_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolfees',
            unique_together=set(),
        ),
    ]
