# Generated by Django 6.0.3 on 2026-04-04 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessmentpassmark_options_and_more'),
        ('fees', '0005_alter_schoolfees_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentfees',
            options={'ordering': ['term__name'], 'verbose_name': 'Assessment Fees', 'verbose_name_plural': 'Assessments Fees'},
        ),
        migrations.RenameField(
            model_name='assessmentfees',
            old_name='notes',
            new_name='description',
        ),
        migrations.AlterUniqueTogether(
            name='assessmentfees',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assessmentfees',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in Uganda Shillings (UGX)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='assessmentfees',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_fee', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentfees',
            name='due_date',
            field=models.DateField(blank=True, help_text='Payment deadline for this fee', null=True),
        ),
        migrations.AddField(
            model_name='assessmentfees',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessmentfees',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='assessmentfees',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='assessmentfees',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='assessmentfees',
            name='discount_reason',
        ),
        migrations.RemoveField(
            model_name='assessmentfees',
            name='is_cleared',
        ),
        migrations.RemoveField(
            model_name='assessmentfees',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='assessmentfees',
            name='student',
        ),
        migrations.RemoveField(
            model_name='assessmentfees',
            name='total_paid',
        ),
        migrations.RemoveField(
            model_name='assessmentfees',
            name='total_required',
        ),
    ]
