# Generated by Django 6.0.3 on 2026-04-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_assessmentfees_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentfees',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assessmentfees',
            name='is_active',
        ),
    ]
