# Generated by Django 6.0.3 on 2026-04-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_remove_assessmentfees_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentfees',
            name='title',
        ),
    ]
