# Generated by Django 5.1.4 on 2026-04-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_teachersubject_subject'),
        ('fees', '0008_remove_assessmentfees_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feespayment',
            name='school_stream',
        ),
        migrations.AddField(
            model_name='feespayment',
            name='amount_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount balance in UGX', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feespayment',
            name='school_class',
            field=models.ForeignKey(help_text='Which Class the student in', on_delete=django.db.models.deletion.CASCADE, related_name='school_class', to='academics.schoolsupportedclasses'),
        ),
    ]
