# Generated by Django 6.0.3 on 2026-03-25 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_motto', models.CharField(blank=True, max_length=200)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('school_stamp', models.ImageField(blank=True, help_text='Official school stamp image for reports and letters', null=True, upload_to='school/')),
                ('head_teacher_signature', models.ImageField(blank=True, null=True, upload_to='school/signatures/')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='MoES Registration Number')),
                ('establishment_year', models.PositiveIntegerField(blank=True, null=True)),
                ('ownership', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('community', 'Community'), ('faith_based', 'Faith-Based / Mission')], default='private', max_length=20)),
                ('school_type', models.CharField(choices=[('day', 'Day School'), ('boarding', 'Boarding School'), ('mixed', 'Day & Boarding')], default='day', max_length=10)),
                ('curriculum', models.CharField(choices=[('uganda', 'Uganda National Curriculum (MoES)'), ('ib', 'International Baccalaureate (IB)'), ('british', 'British Curriculum'), ('mixed', 'Mixed / Custom')], default='uganda', max_length=20)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('central', 'Central Region'), ('eastern', 'Eastern Region'), ('northern', 'Northern Region'), ('western', 'Western Region')], max_length=20)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('po_box', models.CharField(blank=True, max_length=50, verbose_name='P.O. Box')),
                ('phone', models.CharField(max_length=15)),
                ('alt_phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('has_nursery', models.BooleanField(default=True)),
                ('has_primary', models.BooleanField(default=True)),
                ('report_footer_text', models.TextField(blank=True, help_text='Text printed at the bottom of report cards')),
            ],
            options={
                'verbose_name': 'School Setting',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='SchoolAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'Everyone'), ('teachers', 'Teachers & Staff'), ('parents', 'Parents & Guardians'), ('students', 'Students')], default='all', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Date/time after which this announcement is no longer shown', null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_posted', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='academics.schoolclass')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='E.g. "Term 1 2026 Academic Calendar"', max_length=200)),
                ('academic_year', models.CharField(help_text='E.g. 2025/2026', max_length=9)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, help_text='Upload a PDF or image of the printed school calendar', null=True, upload_to='calendars/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False, help_text='Visible to parents and staff on the portal')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendars_created', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='academics.term')),
            ],
            options={
                'verbose_name': 'School Calendar',
                'verbose_name_plural': 'School Calendars',
                'ordering': ['-academic_year', 'term__name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('academic', 'Academic'), ('exam', 'Examination'), ('sports', 'Sports Day / Inter-House'), ('cultural', 'Cultural / Drama'), ('religious', 'Religious / Chapel'), ('holiday', 'Public Holiday'), ('meeting', 'Parents / Staff Meeting'), ('trip', 'School Trip / Excursion'), ('graduation', 'Graduation / Completion'), ('open_day', 'Open Day / Visiting Day'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, help_text='Location e.g. School Playground, Assembly Hall, Kololo Grounds', max_length=200)),
                ('is_whole_school', models.BooleanField(default=True, help_text='Does this event involve the whole school?')),
                ('is_published', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, help_text='Event notice, invitation, or programme', null=True, upload_to='events/')),
                ('organized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_organized', to=settings.AUTH_USER_MODEL)),
                ('school_classes', models.ManyToManyField(blank=True, help_text='Specific classes involved (if not whole-school)', related_name='events', to='academics.schoolclass')),
            ],
            options={
                'verbose_name': 'School Event',
                'verbose_name_plural': 'School Events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('stationery', 'Stationery'), ('uniform', 'School Uniform'), ('scholastic', 'Scholastic Materials / Books'), ('sports', 'Sports / P.E. Kit'), ('equipment', 'Equipment / Tools'), ('other', 'Other')], max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost in UGX (optional)', max_digits=10, null=True)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements_created', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(blank=True, help_text='Leave blank if this requirement applies to all classes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='academics.schoolclass')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='academics.term')),
            ],
            options={
                'verbose_name': 'School Requirement',
                'verbose_name_plural': 'School Requirements',
                'ordering': ['term', 'school_class', 'category'],
            },
        ),
    ]
