# Generated by Django 6.0.3 on 2026-04-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_year'),
        ('school', '0002_remove_schoolannouncement_school_stream_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolrequirement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='schoolrequirement',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='schoolrequirement',
            name='school_stream',
        ),
        migrations.RemoveField(
            model_name='schoolrequirement',
            name='term',
        ),
        migrations.RemoveField(
            model_name='schoolevent',
            name='school_stream',
        ),
        migrations.AlterField(
            model_name='schoolevent',
            name='school_classes',
            field=models.ManyToManyField(blank=True, help_text='Specific classes involved (if not whole-school)', related_name='events', to='academics.schoolsupportedclasses'),
        ),
        migrations.DeleteModel(
            name='SchoolCalendar',
        ),
        migrations.DeleteModel(
            name='SchoolRequirement',
        ),
    ]
