# Generated by Django 5.2.13 on 2026-06-15 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_schoolrequirement_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='Machine-readable identifier used by the frontend. Examples: about_hero, events_hero, team_director', max_length=80, unique=True)),
                ('label', models.CharField(help_text='Human-readable label shown in admin (e.g. "About Us Hero Image")', max_length=150)),
                ('category', models.CharField(choices=[('hero', 'Hero / Banner Image'), ('team', 'Team Member Photo'), ('event', 'Event Image'), ('other', 'Other')], default='other', max_length=10)),
                ('image', models.ImageField(help_text='Upload the image file. Replaces any previous version.', upload_to='dynamic_images/')),
                ('description', models.TextField(blank=True, help_text='Optional notes for admin reference')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dynamic Image',
                'verbose_name_plural': 'Dynamic Images',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fee Category',
                'verbose_name_plural': 'Fee Categories',
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('academic_year', models.CharField(max_length=9)),
                ('grade_level', models.CharField(max_length=50)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='school.feecategory')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'unique_together': {('fee_category', 'academic_year', 'grade_level')},
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='school.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Fee',
                'verbose_name_plural': 'Student Fees',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school.studentfee')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
