# Generated by Django 6.0.3 on 2026-05-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='support_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='support_all_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='support_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='support_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='support_my_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='support_toggle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='support_view',
            field=models.BooleanField(default=False),
        ),
    ]
