# Generated by Django 6.0.3 on 2026-05-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_permission_support_add_permission_support_all_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertypepermission',
            name='can_toggle',
            field=models.BooleanField(default=False),
        ),
    ]
