# Generated by Django 5.2.13 on 2026-06-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='access_token',
            field=models.CharField(help_text='[DEPRECATED] Old authentication token field. No longer used. Kept for backward compatibility. New logins use DRF TokenAuthentication via phone + password.', max_length=64),
        ),
    ]
