# Generated by Django 6.0.3 on 2026-03-26 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(help_text='Auto-generated e.g. REQ2025001', max_length=20, unique=True)),
                ('request_type', models.CharField(choices=[('leave', 'Leave / Absence Request'), ('transfer', 'Transfer Request'), ('meeting', 'Meeting Request'), ('complaint', 'Complaint'), ('fee_query', 'Fees Enquiry'), ('performance', 'Academic Performance Enquiry'), ('health', 'Health / Medical Concern'), ('general', 'General Inquiry'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, help_text='Supporting document e.g. medical certificate', null=True, upload_to='requests/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed / In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not visible to parent)')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member handling this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, help_text='The student this request concerns (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_requests', to='students.student')),
            ],
            options={
                'verbose_name': 'Parent Request',
                'verbose_name_plural': 'Parents Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentsRequestReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='request_replies/')),
                ('is_internal', models.BooleanField(default=False, help_text='If True, this reply is only visible to staff, not the parent')),
                ('is_read_by_parent', models.BooleanField(default=False, help_text='Marked True when the parent views this reply')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('replied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_replies', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communication.parentsrequest')),
            ],
            options={
                'verbose_name': 'Request Reply',
                'verbose_name_plural': 'Request Replies',
                'ordering': ['created_at'],
            },
        ),
    ]
