# Generated by Django 6.0.3 on 2026-03-25 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_title', models.CharField(max_length=255)),
                ('permission_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['permission_title'],
            },
        ),
        migrations.CreateModel(
            name='UserTypePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('parent', 'Parent'), ('teacher', 'Teacher')], max_length=20)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('action_effect', models.CharField(choices=[('can_my', 'Can My  – own records only'), ('can_all', 'Can All – all records')], default='can_my', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_type_assignments', to='authentication.permission')),
            ],
            options={
                'verbose_name': 'User Type Permission',
                'verbose_name_plural': 'User Type Permissions',
                'ordering': ['user_type', 'permission__permission_title'],
                'constraints': [models.UniqueConstraint(fields=('permission', 'user_type'), name='unique_permission_per_user_type')],
            },
        ),
    ]
