# Generated by Django 6.0.3 on 2026-03-31 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['order'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='key',
            field=models.CharField(default=None, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='level_type',
            field=models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='level',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='section',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='stream',
        ),
        migrations.CreateModel(
            name='SchoolStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='academics.schoolclass')),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'ordering': ['class_level__order', 'name'],
                'unique_together': {('class_level', 'name')},
            },
        ),
    ]
