# Generated by Django 6.0.3 on 2026-04-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_schoolclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='school_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.schoolstream'),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='school_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assessments', to='academics.schoolstream'),
        ),
        migrations.AddField(
            model_name='term',
            name='holiday_study_class_stream',
            field=models.ManyToManyField(blank=True, help_text='Classes attending holiday studies e.g. P6, P7', related_name='holiday_study_terms', to='academics.schoolstream'),
        ),
    ]
