# Generated by Django 5.1.4 on 2026-04-02 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_classsubject_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsubject',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='school_stream',
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.schoolsupportedclasses'),
        ),
    ]
