# Generated by Django 6.0.3 on 2026-04-03 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_teachersubject_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherclass',
            options={'ordering': ['school_class'], 'verbose_name': 'Teacher Class Assignment', 'verbose_name_plural': 'Teacher Class Assignments'},
        ),
        migrations.AlterUniqueTogether(
            name='teacherclass',
            unique_together={('school_class',)},
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject', to='academics.schoolsupportedclasses'),
        ),
        migrations.AlterField(
            model_name='teacherclass',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='academics.schoolsupportedclasses'),
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='periods_per_week',
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='term',
        ),
    ]
