# Generated by Django 6.0.3 on 2026-04-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_teacherclass_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherclass',
            unique_together=set(),
        ),
    ]
